channels:
  - conda-forge
dependencies:
  - numpy
  - pip
  - python=3.9
  - jupyter
  - ipykernel
  - nbconvert
  - arviz

  - pip:
      - matplotlib
      - corner
      - chainconsumer==0.34.0
      - numpyro
      - numpyro-ext
      - jaxns==2.4.8
      - git+https://github.com/shishirdholakia/eclipsoid.git
