channels:
  - conda-forge
dependencies:
  - numpy=1.19.2
  - pip=21.0.1
  - python=3.9
  - jupyter
  - ipykernel
  - nbconvert
  - arviz

  - pip:
      - matplotlib==3.4.3
      - corner
      - git+https://github.com/shishirdholakia/jax0planet.git
